# This is a basic workflow to help you get started with Actions

name: CI Arduino

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:
    branches: 
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: arduino/setup-arduino-cli@v1
      - run: |
          mkdir -p "$HOME/Arduino/libraries"
          ln -s "$PWD" "$HOME/Arduino/libraries/."
      - run: arduino-cli lib install "DFRobotDFPlayerMini@1.0.5"
      - run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr@1.8.3
      - run: arduino-cli compile --fqbn arduino:avr:nano:cpu=atmega328old . --warnings more
